# Chargements divers

In [2]:
import math                         # import a package
import numpy as np                  # import a package with specified name
from sklearn import linear_model    # import whole module
from os import mkdir, rmdir, path   # import a funciton
from inspect import getsourcelines  # get function source code
import random
import string
import time
import pandas as pd
import urllib
import zipfile
import matplotlib.pyplot as plt     # for plots
import seaborn as sns               # for plots
import sys

# Utilisation de l'aide

In [10]:
help(mkdir)

Help on built-in function mkdir in module posix:

mkdir(path, mode=511, *, dir_fd=None)
    Create a directory.
    
    If dir_fd is not None, it should be a file descriptor open to a directory,
      and path should be relative; path will then be relative to that directory.
    dir_fd may not be implemented on your platform.
      If it is unavailable, using it will raise a NotImplementedError.
    
    The mode argument is ignored on Windows.



In [11]:
linear_model.LinearRegression?

# Versions de package, localisation des fonctions

In [12]:
print(np.__version__) # obtenir la version d'un package
from inspect import getsourcelines # obtenir le code source de fonctions
getsourcelines(linear_model.LinearRegression)

1.12.1


(['class LinearRegression(LinearModel, RegressorMixin):\n',
  '    """\n',
  '    Ordinary least squares Linear Regression.\n',
  '\n',
  '    Parameters\n',
  '    ----------\n',
  '    fit_intercept : boolean, optional\n',
  '        whether to calculate the intercept for this model. If set\n',
  '        to false, no intercept will be used in calculations\n',
  '        (e.g. data is expected to be already centered).\n',
  '\n',
  '    normalize : boolean, optional, default False\n',
  '        If True, the regressors X will be normalized before regression.\n',
  '        This parameter is ignored when `fit_intercept` is set to False.\n',
  '        When the regressors are normalized, note that this makes the\n',
  '        hyperparameters learnt more robust and almost independent of the number\n',
  '        of samples. The same property is not valid for standardized data.\n',
  '        However, if you wish to standardize, please use\n',
  '        `preprocessing.StandardScaler` b

# 1. Introduction à Python, Numpy et Scipy

# Question 1

In [12]:
# Question 1

def nextpower(n):
    return int(2 ** (math.ceil(math.log(n, 2))))

def nextpowerbis(n):
    sol = 1 
    while sol < n :
        sol *= 2
    return sol

print(nextpower(3))
print(nextpowerbis(3))

4
4


# Question 2

### Méthode 1 (à ne pas utiliser)

In [40]:
word = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
print(word[2],word[5],word[8],word[11],word[14],word[17],word[20],word[23])
# ou word[2],word[5],word[8],word[11],word[14],word[17],word[20],word[23]

C F I L O R U X


### Méthode 2

In [88]:
word = "abcdefghijklmnopqrstuvwxyz"
word[2::3]

'cfilorux'

In [19]:
word = "abcdefghijklmnopqrstuvwxyz"
word2 = word[21:26]
print(word2[0::2])
# ou encore :
alphabet = string.ascii_lowercase
print(alphabet[21:26:2])
print(alphabet[-5::2])

vxz
vxz
vxz


# Question 3

In [31]:
from math import pi
print(pi)
print ("%.9f" % math.pi)
# ou encore
x = round(pi,9)
print('Le nombre pi est égal à ' + str(x))
# ou encore
s = "Le nombre %s est égal à %.9f"
print(s % ("pi", math.pi))

3.141592653589793
3.141592654
Le nombre pi est égal à 3.141592654
Le nombre pi est égal à 3.141592654


# Question 4

### Méthode 1 (à ne pas utiliser)

In [33]:
s="HelLo WordLd!!"
print (s.count('H'),s.count('e'),s.count('l'),s.count('L'),s.count('o'),s.count('W'),s.count('r'),s.count('d'),s.count('!'))
print(len(s))

1 1 1 2 2 1 1 2 2
14


### Méthode 2

In [39]:
s="HelLo WordLd!!"
l=list(s)
#print(list(s))
dico = {}
i=0
for i in range(0,len(s)):
    if l[i] in dico:
        dico[l[i]] += 1
    else :
        dico[l[i]] = 1

print(dico)

# ou encore mieux

print('\n')

s_new = "HelLo WorLd!!"
params = {}

for letter in s_new:
    print(letter)
    if letter not in params:
        params[letter] = 1
    else:
        params[letter] += 1
print(params)

{'H': 1, 'e': 1, 'l': 1, 'L': 2, 'o': 2, ' ': 1, 'W': 1, 'r': 1, 'd': 2, '!': 2}


H
e
l
L
o
 
W
o
r
L
d
!
!
{'H': 1, 'e': 1, 'l': 1, 'L': 2, 'o': 2, ' ': 1, 'W': 1, 'r': 1, 'd': 1, '!': 2}


# Question 5

### Méthode 1
Spécifique à l'encodage de l'alphabet

In [78]:
import random

# On récupère les données
word = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
w=list(word)
wRand=list(word)
random.shuffle(wRand)
print('w est la liste suivante : ' + str(w) + '\n')
print('wRand est la liste suivante : ' + str(wRand) + '\n')

# Création d'un dictionnaire {lettre_de_départ: lettre_encodée}
maping_forward = {}
maping_backward = {}
i = 0
for letter in word:
    # print(letter)
    maping_forward[letter] = wRand[i]
    maping_backward[wRand[i]] = letter
    i += 1
# On a maintenant un dictionnaire qui à chaque lettre fait correspondre sa valeur codée et inversement

# Affichage de la table d'encodage de manière plus visuelle
print('maping_forward est le dictionnaire suivant :')
for keys, values in maping_forward.items():
    print (keys, values)
print('')

print('maping_backward est le dictionnaire suivant :')
for keys, values in maping_backward.items():
    print (keys, values)
print('')

# ou plus simplement mais mins visuel
print(str(maping_forward) + '\n') 
#ou encore
print (maping_forward.items())


w est la liste suivante : ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

wRand est la liste suivante : ['H', 'J', 'D', 'B', 'C', 'I', 'Z', 'W', 'U', 'S', 'E', 'P', 'N', 'R', 'T', 'F', 'G', 'Y', 'O', 'M', 'Q', 'A', 'K', 'X', 'V', 'L']

maping_forward est le dictionnaire suivant :
A H
B J
C D
D B
E C
F I
G Z
H W
I U
J S
K E
L P
M N
N R
O T
P F
Q G
R Y
S O
T M
U Q
V A
W K
X X
Y V
Z L

maping_backward est le dictionnaire suivant :
H A
J B
D C
B D
C E
I F
Z G
W H
U I
S J
E K
P L
N M
R N
T O
F P
G Q
Y R
O S
M T
Q U
A V
K W
X X
V Y
L Z

{'A': 'H', 'B': 'J', 'C': 'D', 'D': 'B', 'E': 'C', 'F': 'I', 'G': 'Z', 'H': 'W', 'I': 'U', 'J': 'S', 'K': 'E', 'L': 'P', 'M': 'N', 'N': 'R', 'O': 'T', 'P': 'F', 'Q': 'G', 'R': 'Y', 'S': 'O', 'T': 'M', 'U': 'Q', 'V': 'A', 'W': 'K', 'X': 'X', 'Y': 'V', 'Z': 'L'}

dict_items([('A', 'H'), ('B', 'J'), ('C', 'D'), ('D', 'B'), ('E', 'C'), ('F', 'I'), ('G', 'Z'), ('H', 'W'), ('I', 'U'

### Méthode 2 
Plus complète et générale avec définition d'une fonction d'encodage

In [85]:
alphabet = string.ascii_letters

indexes = list(range(len(alphabet)))
random.shuffle(indexes)

rosette_forward = {}
rosette_backward = {}
for i, letter in enumerate(alphabet):
    rosette_forward[letter] = alphabet[indexes[i]]
    rosette_backward[alphabet[indexes[i]]] = letter

rosette_forward[" "] = " "
rosette_backward[" "] = " "


def coding(message, rosette, alphabet):
    """Encoding function."""
    message_coded = ""
    for i, letter in enumerate(message):
        if letter in alphabet:
            message_coded += rosette[letter]
        else:
            message_coded += letter
    message_coded = message_coded
    return message_coded


message = "Tu les crois malades? Ça gémit ça rote... ça titube..." \
    "ça pustule... Tu veux vider ta salle d'attente? Instantanément?" \
    "même de ceux qui s'en étranglent à se ramoner les glaviots ?..." \
    "Propose un coup de cinéma!... un apéro gratuit en face!... " \
    "tu vas voir combien qu'il t'en reste...S'ils viennent te relancer " \
    "c'est d'abord parce qu'ils s'emmerdent. " \
    "T'en vois pas un la veille des fêtes..."

# message = "Tu les crois malades ?".decode('utf8')

print(message + "\n")
message_encoded = coding(message, rosette_forward, alphabet)
print(message_encoded + "\n")
message_decoded = coding(message_encoded, rosette_backward, alphabet)
print(message_decoded + "\n")


Tu les crois malades? Ça gémit ça rote... ça titube...ça pustule... Tu veux vider ta salle d'attente? Instantanément?même de ceux qui s'en étranglent à se ramoner les glaviots ?...Propose un coup de cinéma!... un apéro gratuit en face!... tu vas voir combien qu'il t'en reste...S'ils viennent te relancer c'est d'abord parce qu'ils s'emmerdent. T'en vois pas un la veille des fêtes...

dK PXF uavfF hmPmRXF? Çm oéhfr çm avrX... çm rfrKyX...çm sKFrKPX... dK SXKg SfRXa rm FmPPX R'mrrXMrX? bMFrmMrmMéhXMr?hêhX RX uXKg YKf F'XM éramMoPXMr à FX amhvMXa PXF oPmSfvrF ?...LavsvFX KM uvKs RX ufMéhm!... KM mséav oamrKfr XM HmuX!... rK SmF Svfa uvhyfXM YK'fP r'XM aXFrX...I'fPF SfXMMXMr rX aXPmMuXa u'XFr R'myvaR smauX YK'fPF F'XhhXaRXMr. d'XM SvfF smF KM Pm SXfPPX RXF HêrXF...

Tu les crois malades? Ça gémit ça rote... ça titube...ça pustule... Tu veux vider ta salle d'attente? Instantanément?même de ceux qui s'en étranglent à se ramoner les glaviots ?...Propose un coup de cinéma!... un apéro gratuit e

# Question 6

### Méthode 1 (avec boucle)

In [104]:
# Solution 1 : pas la plus efficace
def calc(n):
    result = 2
    for k in range(1, n+1, 1):
        result *= (4*(k**2)) / (4*(k**2)-1)
    return result

t = time.time() #pour mémoriser l'heure exacte avec le début du calcul
print(calc(1000000))
print(time.time() - t) #pour afficher le temps de calcul en prenant l'heure de fin du calcul et en lui enlevant celle de début

3.141591868192149
1.314678430557251


In [111]:
# Solution 2 : permet de réduire le temps de calcul en séparant les éléments à calculer (idée de simplifier les étapes de calcul)
def calc2(n):
    result = 2.
    for k in range(1, n+1, 1):
        int = 4 * k ** 2
        result *= int / (int - 1.)
    return result

t = time.time()
print(calc2(1000000))
print(time.time() - t)

3.141591868192149
0.851525068283081


### Méthode 2 (avec numpy as 'np' et sans boucle) : *beaucoup plus rapide que les autres méthodes*
L'idée est que l'on fait des calculs sur des tableaux.

In [120]:
def calc3(n):
    sol = np.arange(1, n + 1, 1) # np.arange() retourne un objet de type numpy.ndarray.
    sol = sol ** 2 # on met à la puissance 2 tous les éléments du tableau
    sol = 4. * sol / (4. * sol - 1.) #on réutilise le résultat obtenu pour poursuivre le calcul de la même façon
    return 2 * np.prod(sol) # np.prod permet de renvoyer le produit des éléments du tableau selon un axe que l'on peut définir si besoin

t = time.time()
print(calc3(1000000))
print(time.time() - t)

3.141591868192149
0.06620359420776367


# Question 7

In [127]:
def quicksort(ll):
# a sorting algorithm with a pivot value
    if len(ll) <= 1:
        return ll
    else:
        pivot = ll.pop() # pivot = last element of the list ll.
        less = []
        greater = []
        for x in ll:
            if x <= pivot:
                less.append(x) # append 'x' to 'less' : The append() method adds a single item to the existing list. It doesn't return a new list, rather it modifies the original list.
            else:
                greater.append(x) # append 'x' to 'greater'
        return quicksort(less) + [pivot] + quicksort(greater) # concatenate quicksort(less), pivot and quicksort(greater)
# on retourne les quicksort de less et greater car il faut ranger dans l'ordre ces listes avant de concaténer
    
print(quicksort([-2, 3, 5, 1, 3]))

[-2, 1, 3, 3, 5]


# Question 8

In [128]:
matrice = np.random.uniform(-1, 1, (5, 6)) # np.random.uniform(low=0.0, high=1.0, size=None) draws samples from a uniform distribution.
print(matrice)

[[ 0.83904762 -0.25128812  0.69689847  0.98184539  0.81199513 -0.29897788]
 [ 0.53528084  0.77512862 -0.76423965  0.93969754 -0.01448841 -0.2749641 ]
 [ 0.04608056  0.09042215 -0.49616887 -0.07100228 -0.90042839  0.72305366]
 [-0.34817179 -0.07935868  0.78465226  0.78030285 -0.67708278  0.62637545]
 [-0.98784417  0.99987518 -0.93501757 -0.52336733  0.05880751  0.52917806]]


### Solution 1 : multiplication de matrices
Plus difficile à voir car demande d'être à l'aise sur les multiplications de matrices

In [136]:
# first solution: matrix multiplication.
m_int = np.eye(6, 6) # Return a 2-D array with ones on the diagonal and zeros elsewhere.
m_int[1, 0] = -2 # Ligne 1 colonne 0 = -2
m_int[3, 2] = -2 # Ligne 3 colonne 2 = -2
m_int[5, 4] = -2 # Ligne 5 colonne 4 = -2
print(matrice)
print(m_int)
m_sol1 = matrice.dot(m_int) # Dot product of two arrays
print(m_sol1)

[[ 0.83904762 -0.25128812  0.69689847  0.98184539  0.81199513 -0.29897788]
 [ 0.53528084  0.77512862 -0.76423965  0.93969754 -0.01448841 -0.2749641 ]
 [ 0.04608056  0.09042215 -0.49616887 -0.07100228 -0.90042839  0.72305366]
 [-0.34817179 -0.07935868  0.78465226  0.78030285 -0.67708278  0.62637545]
 [-0.98784417  0.99987518 -0.93501757 -0.52336733  0.05880751  0.52917806]]
[[ 1.  0.  0.  0.  0.  0.]
 [-2.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0. -2.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -2.  1.]]
[[ 1.34162386 -0.25128812 -1.26679231  0.98184539  1.40995089 -0.29897788]
 [-1.01497639  0.77512862 -2.64363473  0.93969754  0.5354398  -0.2749641 ]
 [-0.13476373  0.09042215 -0.35416432 -0.07100228 -2.34653572  0.72305366]
 [-0.18945442 -0.07935868 -0.77595344  0.78030285 -1.92983367  0.62637545]
 [-2.98759452  0.99987518  0.11171709 -0.52336733 -0.99954861  0.52917806]]


### Solution 2 : manipulation sur les colonnes
Beaucoup plus simple à mentaliser et également à coder

In [141]:
# second solution: colonnes manipulation
m_sol2 = matrice.copy() # copie la matrice 'matrice' originelle
m_sol2[:, 0] = matrice[:, 0] - 2 * matrice[:, 1] # m_sol[:, 0] est la première colonne
m_sol2[:, 2] = matrice[:, 2] - 2 * matrice[:, 3]
m_sol2[:, 4] = matrice[:, 4] - 2 * matrice[:, 5]
print(m_sol2)

np.allclose(m_sol2, matrice.dot(m_int)) # vérifie qu'on obtient bien le même résultat avec chaque méthode

[[ 1.34162386 -0.25128812 -1.26679231  0.98184539  1.40995089 -0.29897788]
 [-1.01497639  0.77512862 -2.64363473  0.93969754  0.5354398  -0.2749641 ]
 [-0.13476373  0.09042215 -0.35416432 -0.07100228 -2.34653572  0.72305366]
 [-0.18945442 -0.07935868 -0.77595344  0.78030285 -1.92983367  0.62637545]
 [-2.98759452  0.99987518  0.11171709 -0.52336733 -0.99954861  0.52917806]]


True

### Remplacement des valeurs négatives par 0 en utilisant un masque binaire.

In [131]:
# zeroing negative values
m_sol2[m_sol2 <= 0] = 0
print(m_sol2)

[[1.34162386 0.         0.         0.98184539 1.40995089 0.        ]
 [0.         0.77512862 0.         0.93969754 0.5354398  0.        ]
 [0.         0.09042215 0.         0.         0.         0.72305366]
 [0.         0.         0.         0.78030285 0.         0.62637545]
 [0.         0.99987518 0.11171709 0.         0.         0.52917806]]


# Question 9

In [13]:
matrice = np.random.uniform(-1, 1, (5, 20)) # np.random.uniform(low=0.0, high=1.0, size=None) draws samples from a uniform distribution.
G = matrice.T.dot(matrice) # multiplie la transposée de T (matrice.T) avec matrice (.dot(matrice))

# Test G symétrique
print('La matrice G est symétrique : ' + str(np.allclose(G, G.T))) #on compare G et G.T pour savoir si G est symétrique


# Test vp positives - solution 1 :
eig_val, _ = np.linalg.eigh(G)  # Return the eigenvalues and eigenvectors of a Hermitian or symmetric matrix

# Test vp positives - solution 2 : sans les vecteurs propres
eig_val = np.linalg.eigvalsh(G) # Compute the eigenvalues of a Hermitian or real symmetric matrix. Main difference from eigh: the eigenvectors are not computed

idx = eig_val.argsort()[::-1] # .argsort() Returns the indices that would sort an array.
# Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.

print(eig_val[idx])
# Beware some are numerically 0, but negative!

nnz_eig = np.logical_not(np.isclose(eig_val, np.zeros(eig_val.shape)))

# positivity of non-zero eigenvalues:
eig_nnz_val = eig_val[nnz_eig]
print('Are the eigenvalues all positive ? That is ' + str(np.all(eig_nnz_val > 0)))

# rank computation:
rk = str(np.sum(nnz_eig))
print('The rank is : ' + rk)
print('The rank is also: ' + str(np.linalg.matrix_rank(G))) # np.linalg.matrix_rank() Return matrix rank of array using SVD method


La matrice G est symétrique : True
[ 1.12647554e+01  9.69553002e+00  8.05670677e+00  3.35124520e+00
  2.14122132e+00  1.79484461e-15  1.03601613e-15  8.49248810e-16
  6.11999820e-16  5.28340518e-16  1.40124593e-16  5.36261404e-17
 -3.53950644e-17 -7.62152059e-17 -1.94250002e-16 -5.87825272e-16
 -8.04997430e-16 -1.14492334e-15 -1.26606323e-15 -1.94313548e-15]
Are the eigenvalues all positive ? That is True
The rank is : 5
The rank is also: 5


# 2. Introduction à Pandas, Matplotlib, etc.

# Question 10